### PR TITLE
chinese/linux-wps-office-zh_CN: New port

### PR DESCRIPTION
**Pull request by yzgyyang**
WPS Office is a complete office suite with PDF editor. This version is
the localized build for Simplified Chinese with the zh_CN language pack
and other online features.

As many installed files are common with editors/linux-wps-office, only
one version should be installed. CONFLICTS_INSTALL has been set
accordingly for both ports.

Approved by:	lwhsu (mentor), portmgr (no functional changes)

### CODE REVIEW

**Comment by yzgyyang** [comment]
@lwhsu This one is largely based on the editors/linux-wps-office port, but with different rpm package, WWW, EULA etc., so made a few changes only.

**Review by lwhsu — APPROVED** [review]
Approved. BTW why does this needs portmgr's approval?

**Comment by yzgyyang** [comment]
> Approved. BTW why does this needs portmgr's approval?

I updated editors/linux-wps-office without obtaining maintainer's approval😄

**Comment by lwhsu** [comment]
> > Approved. BTW why does this needs portmgr's approval?
> 
> I updated editors/linux-wps-office without obtaining maintainer's approvalsmile

Oh ok, btw this kind of change doesn't really need explicitly stating portmgr's implicitly approval, and after it is not a "no foundational change."

**Comment by yzgyyang** [comment]
> > > Approved. BTW why does this needs portmgr's approval?
> > 
> > 
> > I updated editors/linux-wps-office without obtaining maintainer's approvalsmile
> 
> Oh ok, btw this kind of change doesn't really need explicitly stating portmgr's implicitly approval, and after it is not a "no foundational change."

Does it fall under some kind of exemptions from the maintainer approval thought? Otherwise I'd need to ask the maintainer of `editors/linux-wps-office` to approve this change, right?

**Comment by lwhsu** [comment]
> > > > Approved. BTW why does this needs portmgr's approval?
> > > 
> > > 
> > > I updated editors/linux-wps-office without obtaining maintainer's approvalsmile
> > 
> > 
> > Oh ok, btw this kind of change doesn't really need explicitly stating portmgr's implicitly approval, and after it is not a "no foundational change."
> 
> Does it fall under some kind of exemptions from the maintainer approval thought? Otherwise I'd need to ask the maintainer of `editors/linux-wps-office` to approve this change, right?

Yes, this kind of change is like bumping PORTREVISION to me. Of course it is no harm to ask the maintainer or portmgr.

**Pull request merged**
