### PR TITLE
www/grafana8: New port: Dashboard and graph editor for multiple data stores

### PR DESCRIPTION
**Pull request by yzgyyang**
Updated from grafana7:

- rc-script: grafana_conf renamed to grafana_config
- grafana.conf moved to etc/grafana/grafana.ini
- provisioning dir moved to etc/grafana/provisioning

Changelog:	https://grafana.com/docs/grafana/latest/whatsnew/whats-new-in-v8-0/

PR:		256479
Approved by:	lwhsu (mentor), Robson Mantovani <robsonmantovani@gmail.com>
		(maintainer, www/grafana7)

### CODE REVIEW

**Comment by lwhsu** [comment]
Do we still need other www/grafana*?

BTW we should also encourage maintainer/submitter to ask upstream to update https://grafana.com/grafana/download?pg=get&plcmt=selfmanaged-box1-cta1 to include FreeBSD information

**Comment by yzgyyang** [comment]
> Do we still need other www/grafana*?

In my experience in companies, they are usually using older versions of Grafana, since each major version upgrade involves a considerable amount of breaking changes. Companies that I know are still on two or even three major releases behind the current one. So I would say yes.

> BTW we should also encourage maintainer/submitter to ask upstream to update https://grafana.com/grafana/download?pg=get&plcmt=selfmanaged-box1-cta1 to include FreeBSD information

I agree - though I don't really think they would actively accept it. All the pointers on that page are using the official prebuilt packages and doesn't include community-built ones.

**Comment by lwhsu** [comment]
> > Do we still need other www/grafana*?
> 
> In my experience in companies, they are usually using older versions of Grafana, since each major version upgrade involves a considerable amount of breaking changes. Companies that I know are still on two or even three major releases behind the current one. So I would say yes.
> 

Yes, I agree that old versions is useful and important for users in this case, but we also cannot keep all the old versions only for this reason.  My personal standard is as long as the old versions are still officially supported, then it is fine and reasonable to stay in the ports tree, unless we can't afford the maintenance cost or the new version guanrntees backward compatibility.

So this is more a question and suggestion that we need to check and maybe clean up (some of) the old versions.


> > BTW we should also encourage maintainer/submitter to ask upstream to update https://grafana.com/grafana/download?pg=get&plcmt=selfmanaged-box1-cta1 to include FreeBSD information
> 
> I agree - though I don't really think they would actively accept it. All the pointers on that page are using the official prebuilt packages and doesn't include community-built ones.

Also understandable and that's why it's only encouraging, maybe upstream is willing to include the community supporting information, like many other software do.

**Review by lwhsu — APPROVED** [review]

**Comment by yzgyyang** [comment]
Sounds reasonable, will follow up about these :) Thanks!

**Pull request merged**
